import type { ProductView } from "@/src/modules/catalog/domain/catalog";

export const demoDrinkwareProducts: ProductView[] = [
  {
    id: "prod-mug-vidrio-esmerilado",
    name: "Mug Vidrio Esmerilado",
    slug: "mug-vidrio-esmerilado",
    categorySlug: "mugs-termos",
    categoryName: "Mugs, vasos & termos",
    shortDescription: "Vidrio mate con una presencia ligera y moderna.",
    description:
      "Mug de vidrio esmerilado de 11 oz con superficie preparada para sublimación y asa transparente.",
    basePrice: 24000,
    featured: false,
    customizable: true,
    imageUrl: "/products/mockups/mug-vidrio-esmerilado.webp",
    gallery: ["/products/mockups/mug-vidrio-esmerilado.webp"],
    badge: "Acabado mate",
    leadTime: "3–5 días hábiles",
    techniques: ["Sublimación"],
    variants: [
      {
        id: "var-mug-glass-frosted-11",
        sku: "AP-MUG-GLS-11",
        name: "Esmerilado / 11 oz",
        color: "Translúcido",
        colorHex: "#e7ebeb",
        size: "11 oz",
        material: "Vidrio esmerilado",
        technique: "Sublimación",
        priceModifier: 0,
        available: true,
      },
    ],
    printAreas: [
      {
        id: "area-mug-glass-front",
        key: "front",
        name: "Frente",
        view: "FRONT",
        x: 14,
        y: 24,
        width: 53,
        height: 47,
        realWidthCm: 9,
        realHeightCm: 8,
      },
    ],
    highlights: ["11 oz", "Vidrio esmerilado", "Sublimación de alta definición"],
  },
  {
    id: "prod-mug-peltre",
    name: "Mug Peltre Sublimable",
    slug: "mug-peltre-sublimable",
    categorySlug: "mugs-termos",
    categoryName: "Mugs, vasos & termos",
    shortDescription: "Estética clásica de camping con borde negro.",
    description:
      "Mug de peltre blanco de 12 oz, liviano y resistente, con recubrimiento apto para sublimación.",
    basePrice: 27000,
    featured: false,
    customizable: true,
    imageUrl: "/products/mockups/mug-peltre.webp",
    gallery: ["/products/mockups/mug-peltre.webp"],
    badge: "Estilo outdoor",
    leadTime: "3–5 días hábiles",
    techniques: ["Sublimación"],
    variants: [
      {
        id: "var-mug-enamel-white-12",
        sku: "AP-MUG-ENM-12",
        name: "Blanco / borde negro / 12 oz",
        color: "Blanco",
        colorHex: "#f7f6f2",
        size: "12 oz",
        material: "Peltre esmaltado",
        technique: "Sublimación",
        priceModifier: 0,
        available: true,
      },
    ],
    printAreas: [
      {
        id: "area-mug-enamel-front",
        key: "front",
        name: "Frente",
        view: "FRONT",
        x: 17,
        y: 31,
        width: 53,
        height: 40,
        realWidthCm: 9,
        realHeightCm: 7,
      },
    ],
    highlights: ["12 oz", "Borde negro", "Liviano y resistente"],
  },
  {
    id: "prod-vaso-termico",
    name: "Vaso Térmico 12 oz",
    slug: "vaso-termico-12-oz",
    categorySlug: "mugs-termos",
    categoryName: "Mugs, vasos & termos",
    shortDescription: "Formato compacto con tapa para bebidas frías o calientes.",
    description:
      "Vaso térmico de acero inoxidable de doble pared, acabado blanco mate y tapa transparente ajustada.",
    basePrice: 39000,
    featured: true,
    customizable: true,
    imageUrl: "/products/mockups/vaso-termico.webp",
    gallery: ["/products/mockups/vaso-termico.webp"],
    badge: "Nuevo",
    leadTime: "3–5 días hábiles",
    techniques: ["Sublimación", "Vinilo premium"],
    variants: [
      {
        id: "var-tumbler-white-12",
        sku: "AP-TMB-WHT-12",
        name: "Blanco mate / 12 oz",
        color: "Blanco",
        colorHex: "#f4f3ef",
        size: "12 oz",
        material: "Acero inoxidable",
        technique: "Sublimación",
        priceModifier: 0,
        available: true,
      },
    ],
    printAreas: [
      {
        id: "area-tumbler-front",
        key: "front",
        name: "Frente",
        view: "FRONT",
        x: 30,
        y: 27,
        width: 40,
        height: 48,
        realWidthCm: 8,
        realHeightCm: 9,
      },
    ],
    highlights: ["12 oz", "Doble pared", "Tapa transparente"],
  },
  {
    id: "prod-vaso-vidrio-bambu",
    name: "Vaso Vidrio con Bambú",
    slug: "vaso-vidrio-bambu-16-oz",
    categorySlug: "mugs-termos",
    categoryName: "Mugs, vasos & termos",
    shortDescription: "Vidrio esmerilado, tapa de bambú y pitillo reutilizable.",
    description:
      "Vaso recto de vidrio esmerilado de 16 oz con tapa de bambú natural y pitillo transparente.",
    basePrice: 32000,
    featured: false,
    customizable: true,
    imageUrl: "/products/mockups/vaso-vidrio-bambu.webp",
    gallery: ["/products/mockups/vaso-vidrio-bambu.webp"],
    badge: "Eco favorito",
    leadTime: "3–5 días hábiles",
    techniques: ["Sublimación"],
    variants: [
      {
        id: "var-glass-bamboo-frosted-16",
        sku: "AP-GLS-BAM-16",
        name: "Esmerilado / bambú / 16 oz",
        color: "Translúcido",
        colorHex: "#e5e8e6",
        size: "16 oz",
        material: "Vidrio y bambú",
        technique: "Sublimación",
        priceModifier: 0,
        available: true,
      },
    ],
    printAreas: [
      {
        id: "area-glass-bamboo-front",
        key: "front",
        name: "Frente",
        view: "FRONT",
        x: 37,
        y: 34,
        width: 26,
        height: 47,
        realWidthCm: 7,
        realHeightCm: 13,
      },
    ],
    highlights: ["16 oz", "Tapa de bambú", "Pitillo reutilizable"],
  },
];
